solved issue #7
thlorenz/resolve-bin pull request #8
Opened 2021-05-28 11:31 UTC by bingtimren

This PR solves issue #7 

With this PR resolve-bin now works with packages that does not has "main" field in "package.json". One example is "open-cli".

Also added tests.

Please accept this PR and publish a new release. Thanks

2021-05-28 17:59 UTC, bendrucker requested changes
Nice! If you can fix the copied bit in the example that refers to Mocha, happy to get this merged and released as a patch.

2021-05-28 17:59 UTC, bendrucker commented on examples/open-cli.js
> +//  },
Copy pasted?

2021-05-30 23:40 UTC, bingtimren commented on examples/open-cli.js
> +//  },
Woops, copy pasted indeed. Fixed.

2021-05-31 12:48 UTC, bingtimren commented
Found another example "dependency-cruise", the "package.json" cannot be resolved. Therefore changed the code to first attempt "require.resolve", which is identical with the current behaviour, and only attempts to resolve "package.json" if it fails.

2021-06-01 18:45 UTC, merged

2021-07-08 18:44 UTC, bendrucker commented
Done!